version: '3'
services:
  front-react:
    build:
      context: ./client

    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - '3000:3000'
    container_name: new-squadhelp-front-react

  server-dev:
    build:
      context: ./server

    environment:
      NODE_ENV: development
    ports:
      - '5000:5000'
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules
    container_name: new-squadhelp-server-dev

  mongo-dev:
    image: mongo:4.4.6-bionic
    ports:
      - '27017:27017'
    container_name: new-squadhelp-mongo-dev

  db-dev:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - '5432:5432'
    container_name: new-squadhelp-db-dev

volumes:
  server-dev:
